### ISSUE TITLE
Is it possible to run this package only with RGB images?

### ISSUE THREAD

**Issue by TrinhNC** [zhangbaozhe/icg_ros#3]
Hi,
I'm wondering if this can be run without depth information or not?

**Comment by zhangbaozhe** [comment]
I'm not sure whether ICG supports it. I think probably it can be done because depth information as in ICG is another term in the optimization function besides the region (color) term. Also, the code in ICG suggests no matter for color or depth information, they use a `modality` abstract class https://github.com/zhangbaozhe/icg_ros/blob/0c3f0f8e06a76c97738d92983bbe95aef64a8d2c/include/icg/modality.h#L54 for future optimization. I think maybe we can disable the depth and only use the region modality. 

Now in my wrapper, I haven't supported it yet and I am not sure whether I'm gonna support it. If you are looking for only region-based pose tracking methods, I suggest you refer to the work before ICG which is [RBGT](https://github.com/DLR-RM/3DObjectTracking/tree/master/RBGT).
